### ISSUE TITLE
Todos 1

### ISSUE THREAD

**Issue by dandolo** [oezilot/Website#1]
- [x] Hover effect index.html does not work on all buttons
- [x] Only the first button redirects correctly.
- [x] Add a home button on each subpage to navigate back
- [x] Use `background-color` instead of some rectangle to color tables
- [x] Add content

**Comment by oezilot** [comment]
- [ ] socials (icons) auf der startseite!
- [ ] grösse der bilder in den tabellen wo es mehrere bilder gibt anpassen damit es schöner aussieht
- [ ] für den home-link ein bild benutzen und dieses schöner positionieren
